
import { Navbar } from './components';
import './globals.css'
import type { Metadata } from 'next'

export const viewportMeta = (
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
  />
);

export const metadata: Metadata = {
  title: 'Gro',
  description: 'Generated by create next app',
}
export default function RootLayout({

  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className="overflow-x-hidden">
      <body className='relative overflow-x-hidden' suppressHydrationWarning={true}>
        <div className='overflow-hidden'>
          <Navbar/>
        {children}
        {viewportMeta}
        </div>
        
      </body>
    </html>
  )
}
